name: Angular CI - Build to Docs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  # manual run

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ng18

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js (with cache)
        uses: actions/setup-node@v4
        with:
          node-version: '24.2.0'
          cache: 'npm'
          cache-dependency-path: 'ng18/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app (production to ../docs)
        run: |
          ng build --configuration production --output-path ../../docs --base-href /non4me/datalite/

      - name: Verify build output
        run: |
          ls -la ../../docs  # Проверить, что файлы в ./docs (index.html, assets etc.)
          # Опционально: test на наличие index.html
          if [ ! -f "../../docs/index.html" ]; then exit 1; fi

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'ng18/package-lock.json'

      - name: Install dependencies and build
        working-directory: ./ng18
        run: |
          npm ci
          ng build --configuration production --output-path ../../docs

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact (static files from ./docs)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4