name: Angular CI - Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ng18  # All commands run in the ./ng18 directory

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch all branches and tags for a complete checkout
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use Node.js 20 LTS for Angular 18 compatibility
          cache: 'npm'
          cache-dependency-path: 'ng18/package-lock.json'  # Cache based on package-lock.json

      - name: Install dependencies
        run: npm ci  # Use npm ci for clean, reproducible installs in CI

      - name: Build Angular app (production)
        run: npm run build:prod  # Assumes a build:prod script in package.json for optimized build; or use 'ng build --configuration production'

      - name: Verify build output
        run: |
          # Check if the dist folder was created (default output path)
          if [ ! -d "dist/ng18" ]; then
            echo "Build failed: dist/ng18 directory not found"
            exit 1
          fi
          ls -la dist/ng18  # List contents for verification
          # Ensure key files exist
          if [ ! -f "dist/ng18/index.html" ]; then
            echo "Build failed: index.html not found in dist"
            exit 1
          fi